server:
  port: 8080
  context-path: /api

#users-service:
#  ribbon:
##    listOfServers: localhost:8082,localhost:8002
#    listOfServers: localhost:8082
#
#todo-service:
#  ribbon:
##    listOfServers: localhost:8088,localhost:8001
#    listOfServers: localhost:8088


zuul:
  ignoredServices: '*'
  routes:
    todos:
      path: /todos/**
#      url: http://todo-service:8088
      url: http://localhost:8088
#      serviceId: todoService
      stripPrefix: false
      sensitiveHeaders:

    tags:
      path: /tags/**
#      url: http://todo-service:8088
      url: http://localhost:8088
      stripPrefix: false
      sensitiveHeaders:

    users:
      path: /users/**
#      url: http://user-service:8082
      url: http://localhost:8082
#      serviceId: userService
      stripPrefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000


#spring:
#  application:
#    name: gateway
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        health-check-path: /api/health

